# Generated by Django 5.0.3 on 2024-03-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already used by an account!'}, max_length=254, unique=True),
        ),
    ]
