# Generated by Django 5.0.3 on 2024-03-15 15:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))]),
        ),
    ]
